{
    "openapi": "3.0.0",
    "servers": [
        {
            "url": "http://localhost:8080"
        }
    ],
    "info": {
        "title": "Fn serverless application API spec",
        "description": "Functions spec that describes Fn-powered serverless application",
        "version": "0.0.1"
    },
    "paths": {
        "/r/app/test/{username}": {
            "post": {
                "description": "Creates a user and then sends a generated password email",
                "summary": "Create User",
                "operationId": "createUser",
                "parameters": [
                    {
                        "description": "The username for a user to create",
                        "name": "username",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "pattern": "^[-a-z0-9_]+$"
                        }
                    },
                    {
                        "description": "The user's Membership Type",
                        "name": "membershipType",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "enum": [
                                "premium",
                                "standard"
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "create a user",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "description": "example",
                                    "type": "object",
                                    "title": "JSON API Schema",
                                    "properties": {
                                        "SomeObject": {
                                            "type": "object",
                                            "properties": {
                                                "SomeAttribute": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "object",
                                            "properties": {
                                                "fields": {
                                                    "type": "string"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
